#!/bin/sh
# ==============================================================================
# Script:       26.remove_inversion.sh
# Description:  Remove putative inversion regions from per-chromosome VCFs and
#               produce a genome-wide inversion-free dataset for population
#               structure analyses.
#
#               Pipeline:
#                 1. Exclude inversion SNPs from affected chromosomes using
#                    vcftools --exclude-positions and the .pos files produced
#                    by vcftools --012 during local PCA (21a.local_pca.sh).
#                 2. Concatenate filtered chromosomes into a single genome-wide VCF.
#                 3. Convert merged VCF to PLINK binary format and write SNP list.
#
# Input:        Per-chromosome VCFs from 20a.prepare_lostruct.sh
#               Per-inversion .pos files from 21a.local_pca.sh (--012 output)
#
# Output:       Per-chromosome filtered VCFs in NO_INV_DIR
#               Pmax_no_inversion.vcf  — genome-wide inversion-free VCF
#               Pmax_no_inversion.bed/.bim/.fam — PLINK binary dataset
#               Pmax_no_inversion.snplist — SNP list for downstream analyses
#
# Note:         Run as an interactive qlogin job — no SGE submission required.
# ==============================================================================

# ------------------------------------------------------------------------------
# Load required modules
# ------------------------------------------------------------------------------

. /etc/profile.d/modules.sh

module load vcftools/0.1.16
module load bcftools/1.20
module load plink/1.9

# ------------------------------------------------------------------------------
# Path configuration
# ------------------------------------------------------------------------------

VCF_DIR=/simone/pmax2023/out/20.lostruct/vcf
INV_DIR=/simone/pmax2023/out/20.lostruct/inversions
NO_INV_DIR=/simone/pmax2023/out/22.no_inversion
SNP_DIR=/simone/pmax2023/out/file_lists

mkdir -p "${NO_INV_DIR}"

echo "=================================================="
echo "Start time: $(date)"
echo "VCF dir:    ${VCF_DIR}"
echo "Output dir: ${NO_INV_DIR}"
echo "=================================================="

# ==============================================================================
# STEP 1: Exclude inversion SNPs from affected chromosomes
# ==============================================================================
# SNP positions to exclude are taken from the .pos files generated by
# vcftools --012 during local PCA (21a.local_pca.sh). Chromosomes carrying
# multiple inversions are filtered sequentially, with each pass using the
# filtered output of the previous step as input.

echo ""
echo "[$(date)] === Filtering inversion regions per chromosome ==="

# ------------------------------------------------------------------------------
# Chr 02 — LGC02
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736839.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736839.1.filtered"

# ------------------------------------------------------------------------------
# Chr 08 — LGC08.01 then LGC08.02 (two inversions, filtered sequentially)
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736845.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC08.01.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736845.1.filtered_t1"

vcftools \
    --vcf "${NO_INV_DIR}/LR736845.1.filtered_t1.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC08.02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736845.1.filtered"

# ------------------------------------------------------------------------------
# Chr 09 — LGC09
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736846.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC09.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736846.1.filtered"

# ------------------------------------------------------------------------------
# Chr 11 — LGC11
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736848.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC11.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736848.1.filtered"

# ------------------------------------------------------------------------------
# Chr 13 — LGC13.01 then LGC13.02 (two inversions, filtered sequentially)
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736850.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC13.01.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736850.1.filtered_t1"

vcftools \
    --vcf "${NO_INV_DIR}/LR736850.1.filtered_t1.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC13.02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736850.1.filtered"

# ------------------------------------------------------------------------------
# Chr 15 — LGC15
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736852.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC15.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736852.1.filtered"

# ------------------------------------------------------------------------------
# Chr 17 — LGC17.01 then LGC17.02 (two inversions, filtered sequentially)
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736854.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC17.01.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736854.1.filtered_t1"

vcftools \
    --vcf "${NO_INV_DIR}/LR736854.1.filtered_t1.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC17.02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736854.1.filtered"

# ------------------------------------------------------------------------------
# Chr 18 — LGC18.01, LGC18.01_02, LGC18.03, LGC18.04, LGC18.02
#          (five inversions, filtered sequentially)
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736855.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC18.01.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736855.1.filtered_t1"

vcftools \
    --vcf "${NO_INV_DIR}/LR736855.1.filtered_t1.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC18.01_02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736855.1.filtered_t2"

vcftools \
    --vcf "${NO_INV_DIR}/LR736855.1.filtered_t2.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC18.03.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736855.1.filtered_t3"

vcftools \
    --vcf "${NO_INV_DIR}/LR736855.1.filtered_t3.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC18.04.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736855.1.filtered_t4"

vcftools \
    --vcf "${NO_INV_DIR}/LR736855.1.filtered_t4.recode.vcf" \
    --exclude-positions "${INV_DIR}/LGC18.02.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736855.1.filtered"

# ------------------------------------------------------------------------------
# Chr 19 — LGC19.01
# ------------------------------------------------------------------------------
vcftools \
    --vcf "${VCF_DIR}/LR736856.1.vcf" \
    --exclude-positions "${INV_DIR}/LGC19.01.012.pos" \
    --recode --recode-INFO-all \
    --out "${NO_INV_DIR}/LR736856.1.filtered"

# ------------------------------------------------------------------------------
# Copy chromosomes without inversions into the output directory
# ------------------------------------------------------------------------------
# Chr 01, 03, 04, 05, 06, 07, 10, 12, 14, 16 carry no putative inversions
# and are used as-is.

for CHR in LR736838.1 LR736840.1 LR736841.1 LR736842.1 LR736843.1 \
           LR736844.1 LR736847.1 LR736849.1 LR736851.1 LR736853.1; do
    cp "${VCF_DIR}/${CHR}.vcf" "${NO_INV_DIR}/"
done

echo "[$(date)] Per-chromosome filtering complete"

# ==============================================================================
# STEP 2: Concatenate all chromosomes into a single genome-wide VCF
# ==============================================================================
# Filtered VCFs are used for chromosomes with inversions;
# original VCFs are used for chromosomes without.

echo ""
echo "[$(date)] === Merging all chromosomes ==="

cd "${NO_INV_DIR}"

bcftools concat \
    -o Pmax_no_inversion.vcf \
    LR736838.1.vcf \
    LR736839.1.filtered.recode.vcf \
    LR736840.1.vcf \
    LR736841.1.vcf \
    LR736842.1.vcf \
    LR736843.1.vcf \
    LR736844.1.vcf \
    LR736845.1.filtered.recode.vcf \
    LR736846.1.filtered.recode.vcf \
    LR736847.1.vcf \
    LR736848.1.filtered.recode.vcf \
    LR736849.1.vcf \
    LR736850.1.filtered.recode.vcf \
    LR736851.1.vcf \
    LR736852.1.filtered.recode.vcf \
    LR736853.1.vcf \
    LR736854.1.filtered.recode.vcf \
    LR736855.1.filtered.recode.vcf \
    LR736856.1.filtered.recode.vcf

echo "[$(date)] Merged VCF written: Pmax_no_inversion.vcf"

# ==============================================================================
# STEP 3: Convert to PLINK binary format and write SNP list
# ==============================================================================

echo ""
echo "[$(date)] === Converting to PLINK binary format ==="

plink --vcf Pmax_no_inversion.vcf --allow-extra-chr --make-bed --recode --out Pmax_no_inversion

echo "[$(date)] Writing SNP list"

plink --file Pmax_no_inversion --allow-extra-chr --write-snplist --out Pmax_no_inversion

echo ""
echo "[$(date)] Done."
echo "Outputs:"
echo "  Genome-wide VCF:  ${NO_INV_DIR}/Pmax_no_inversion.vcf"
echo "  PLINK binary:     ${NO_INV_DIR}/Pmax_no_inversion.bed/.bim/.fam"
echo "  SNP list:         ${SNP_DIR}/Pmax_no_inversion.snplist"
echo "=================================================="
echo "End time: $(date)"
echo "=================================================="
